name: Build and deploy React.js app Onefps Shared Web App to Azure Web App

on:
  push:
    branches:
       - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
     steps:
     - name: Print GitHub Event
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
